name: Ansible Lint

on:
  push:
    branches: [main, dev-bare-repo]
  pull_request:
    branches: [main]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint install.yml install-system.yml system.yml setup_vcpkg.yml
